### ISSUE TITLE
PHP Fatal error:  Call to undefined function event_base_new() in  battleship-master\server\Core\Listener.php on line 15

### ISSUE THREAD

**Issue by tablecell** [lan143/battleship#1]
016.04.30 09:38:44: -----------------------------
2016.04.30 09:38:44: |        Game server        |
2016.04.30 09:38:44: |    devel fuck the shit    |
2016.04.30 09:38:44: -----------------------------
PHP Fatal error:  Call to undefined function event_base_new()

**Comment by lan143** [comment]
You need install libevent on php.
